name: First Workflow
on: workflow_dispatch #user manually trigger the workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done -  bye!"
